import Image from 'next/image'
import styles from './page.module.css'
import Card from '../components/card'

export const metadata = {
  title: 'Pokédex',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <main className={styles.main}>
      <div className={styles.center}>
        <Image
          src="/pokedex.jpg"
          alt="Next.js Logo"
          width={684}
          height={523}
          priority
        />
      </div>
      <div className={styles.grid}>
        <Card href={'/pokedex'} title={'Pokédex'} text={'Search your pokémon!'} />
        <Card href={'/about'} title={'Catch calc'} text={'Catch rate!'} />
        <Card href={'/odds'} title={'Odds calc'} text={'Odds calculator!'} />
        <Card href={'/type-chart'} title={'Type chart'} text={'Type chart!'} />
      </div>
    </main>
  )
}
