import Image from 'next/image'
import styles from './page.module.css'
import Card from '../components/card'
import Link from 'next/link'

export const metadata = {
  title: 'Pokédex',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <main className={styles.main}>
      <div className={styles.center}>
        <Image
          src="/pokedex.jpg"
          alt="Next.js Logo"
          width={684}
          height={523}
          priority
        />
      </div>
      <div className={styles.grid}>
        <Card href={'/pokedex'} title={'Pokédex'} text={'Search your pokémon!'} />
        <Link
          href="/about"
          className={styles.card}
          rel="noopener noreferrer"
        >
          <h2>
            Catch calc<span>-&gt;</span>
          </h2>
          <p>Catch calculator</p>
        </Link>
        <Link
          href="/odds"
          className={styles.card}
          rel="noopener noreferrer"
        >
          <h2>
            Odds calc <span>-&gt;</span>
          </h2>
          <p>Odds calculator</p>
        </Link>
        <Link
          href="/type-chart"
          className={styles.card}
          // rel="noopener noreferrer"
        >
          <h2>
            Type chart <span>-&gt;</span>
          </h2>
          <p>
            Type chart
          </p>
        </Link>
      </div>
    </main>
  )
}
